/* ------------------------------------------------------------------
   derive-skin.js
   Build a complete, contrast-checked skin from ONE seed color + a
   light/dark mode + a form preset. The seed becomes --c-brand; every
   other color token is derived and WCAG-corrected. Mirrors the
   philosophy of skin-from-photo.js (nobody hand-picks 14 colors) but
   driven by a single chosen brand color instead of a photo.

   exports: derive(seed, mode) -> {token: value}
            buildSkinCss({name, seed, mode, preset}) -> css string
   ------------------------------------------------------------------ */
const { rgbToHsl, hexToRgb, hsl, adjustL, contrast, pickReadable, ensureContrast } = require('./color');
const forms = require('./forms');

/* derive the 14 color tokens from a single brand seed */
function derive(seed, mode) {
  const [h, s] = rgbToHsl(hexToRgb(seed));
  const dark = mode === 'dark';
  const dir = dark ? 'brighten' : 'darken';        // direction that makes text legible

  // backgrounds carry a faint hint of the brand hue
  const bg      = dark ? hsl(h, Math.min(s * 0.40, 0.18), 0.08)
                       : hsl(h, Math.min(s * 0.15, 0.06), 0.985);
  const bgAlt   = dark ? hsl(h, Math.min(s * 0.40, 0.18), 0.12)
                       : hsl(h, Math.min(s * 0.15, 0.06), 0.93);
  const bgDeep  = dark ? hsl(h, Math.min(s * 0.50, 0.22), 0.04)
                       : hsl(h, Math.min(s * 0.50, 0.25), 0.12);
  const surface = dark ? hsl(h, Math.min(s * 0.35, 0.16), 0.13)
                       : hsl(h, Math.min(s * 0.10, 0.04), 0.995);

  // ink — high contrast on bg, faintly hue-tinted
  const ink     = ensureContrast(hsl(h, 0.12, dark ? 0.93 : 0.16), bg, 8,   dir);
  const inkSoft = ensureContrast(hsl(h, 0.10, dark ? 0.72 : 0.42), bg, 4.5, dir);

  // brand = the seed, pushed until it's legible AS TEXT on bg (eyebrows/links use it)
  let brand = ensureContrast(seed, bg, 4.5, dir);
  let brandInk = pickReadable(brand);
  let guard = 0;
  while (contrast(brand, brandInk) < 4.5 && guard < 20) {
    brand = adjustL(brand, brandInk === '#ffffff' ? -0.04 : 0.04);
    brandInk = pickReadable(brand);
    guard++;
  }
  const brandDeep = adjustL(brand, -0.10);

  // accent — a hue-shifted companion, also legible on bg
  const accent = ensureContrast(
    hsl((h + 150) % 360, Math.max(s * 0.7, 0.30), dark ? 0.55 : 0.45), bg, 4.5, dir);

  const line       = dark ? hsl(h, 0.12, 0.18) : hsl(h, 0.10, 0.88);
  const lineStrong = dark ? hsl(h, 0.12, 0.30) : hsl(h, 0.10, 0.80);

  return {
    '--c-bg': bg, '--c-bg-alt': bgAlt, '--c-bg-deep': bgDeep, '--c-surface': surface,
    '--c-ink': ink, '--c-ink-soft': inkSoft,
    '--c-ink-invert': '#ffffff', '--c-ink-invert-soft': 'rgba(255,255,255,0.72)',
    '--c-brand': brand, '--c-brand-deep': brandDeep, '--c-brand-ink': brandInk,
    '--c-accent': accent, '--c-line': line, '--c-line-strong': lineStrong,
  };
}

function buildSkinCss({ name, seed, mode, preset }) {
  const form = forms[preset] || forms.modern;
  const palette = derive(seed, mode);
  const lines = o => Object.entries(o).map(([k, v]) => `  ${k}: ${v};`).join('\n');
  return (
`/* ============================================================
   GENERATED SKIN — ${name}
   Seed: ${seed}   ·   Mode: ${mode}   ·   Form: ${preset}
   Brand-seeded palette, WCAG-corrected. Generated by the builder's
   "New skin" button (scaffold/derive-skin.js) — regenerate, don't hand-edit.
   ============================================================ */
@import url('${form.fontImport}');

:root {
  /* ---- palette (derived from seed ${seed}, ${mode} mode) ---- */
${lines(palette)}

  /* ---- form preset: ${preset} ---- */
${lines(form.tokens)}
}
${form.flourishes ? '\n' + form.flourishes + '\n' : ''}`
  );
}

module.exports = { derive, buildSkinCss };
